jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Install dependencies
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode
        --show-version --file pom.xml
    - continue-on-error: true
      name: Build with Maven
      run: mvn test --batch-mode --file pom.xml
    strategy:
      matrix:
        java-version:
        - 8
        platform:
        - ubuntu-16.04
name: Build with Maven
on:
  repository_dispatch:
    types: trigger-ga___build-2.x.yaml
