jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Install dependencies
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode
        --show-version --file pom.xml
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install --batch-mode && mvn test -Pskip-default-test -Pintegration-test
        --batch-mode --file pom.xml
    - continue-on-error: true
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      id: refs
      if: ${{ matrix.java-version == '8' }}
      name: Set branch name and PR number
      run: 'echo "::set-output name=branch_name::${BRANCH_NAME_OR_REF#refs/heads/}"

        echo "::set-output name=pr_number::$(jq --raw-output .pull_request.number
        "$GITHUB_EVENT_PATH")"

        '
    - continue-on-error: true
      env:
        CI_BRANCH: ${{ steps.refs.outputs.branch_name }}
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after
          }}/checks
        CI_NAME: Github
        CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
      if: ${{ matrix.java-version == '8' && steps.refs.outcome == 'success' }}
      name: Update coverage data
      run: mvn jacoco:report coveralls:report --batch-mode --file pom.xml --no-transfer-progress
        -DrepoToken=${{ secrets.COVERALLS_TOKEN }}
    strategy:
      matrix:
        java-version:
        - 8
        - 11
        - 17
        platform:
        - ubuntu-latest
name: Build with Maven
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
permissions: read-all
